apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: name
  namespace: dognauts-logreg
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - env:
          - name: GUNICORN_WORKERS
            value: '2'
          - name: GUNICORN_THREADS
            value: '2'
          livenessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          name: logisticregression
          readinessProbe:
            failureThreshold: 200
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 1Gi
    graph:
      envSecretRefName: seldon-secret
      implementation: MLFLOW_SERVER
      modelUri: s3://dognauts-logreg/1/a74257d7a76c493ba1a1ba1b9a92808d/artifacts/model
      name: logisticregression
    name: logisticregression
    replicas: 1
